title: <p align="center"> Sai jyoti </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/saijyoti-patnaik-303ba315b/">LinkedIn</a> |
  <a href="https://github.com/Syjo-712">GitHub</a>
  
  <br>   
  I'm studying on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Worked with Teksystems Global services.
  Working in Salesforce domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
